package com.a506.webrtc.stomp.entity;

public enum EventType {
	ROOM_UPDATE, ROOM_DELETE, ROOM_JOIN, ROOM_OUT,
	CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE, LOUNGE_CREATE, LOUNGE_UPDATE, LOUNGE_DELETE
}
